name: Or Condition Demo
on: workflow_dispatch
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run for tiru form tirucloud
        if: github.actor == 'god' || github.actor == 'tiru'
        run: echo "It is triggered by either god or tiru"
